name: 'Test'
on:
  push: {}
jobs:
  maven-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elasticsearch: 7.7.0
            lucene: 8.5.1
          - elasticsearch: 7.7.1
            lucene: 8.5.1
          - elasticsearch: 7.8.1
            lucene: 8.5.1
          - elasticsearch: 7.9.3
            lucene: 8.6.2
          - elasticsearch: 7.10.2
            lucene: 8.7.0
          - elasticsearch: 7.11.2
            lucene: 8.7.0
          - elasticsearch: 7.12.0
            lucene: 8.8.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: mvn -B -Delasticsearch.version=${{ matrix.elasticsearch }} -Dlucene.version=${{ matrix.lucene }} test
